# Data Analytics with Pandas

In this tutorial we will learn how to use pandas for data analysis. You can think of pandas as an extremely powerful version of Excel, with a lot more features. 

A few basic concepts to be covered include:

    1. Pandas: creating data(lists, Series, Data Frames); 
    2. Dealing with already existing data (Data Input and Output)
    3. Data Manipulation: Methods and Operations on Data
    4. Exercise- Men at work!!!

In [1]:
import pandas as pd
from pandas import DataFrame, Series

### Creating Data

In [3]:
#creating series from lists
names = ['Rexy', 'Raphael', 'Rita', 'Razel', 'Randiel']
size = [70, 75, 78, 73, 72]
names

['Rexy', 'Raphael', 'Rita', 'Razel', 'Randiel']

In [4]:
about = pd.Series(data = names, index = size)
about

70       Rexy
75    Raphael
78       Rita
73      Razel
72    Randiel
dtype: object

In [5]:
about[70]

'Rexy'

In [6]:
stu = pd.Series(data = ['Damalie', 'Damon', 'Durim', 'Donald'],index = ['A', 'B', 'C', 'D'])
stu

A    Damalie
B      Damon
C      Durim
D     Donald
dtype: object

In [7]:
stu['D']

'Donald'

In [8]:
#Creating Series from dictionaries
cities= {0:'Kampala', 1:'Arusha', 2:'Nyeri', 3: 'Addis', 4:'Accra'}

In [9]:
pd.Series(cities)

0    Kampala
1     Arusha
2      Nyeri
3      Addis
4      Accra
dtype: object

In [10]:
#creating a dataframe
df = pd.DataFrame(columns = 'City Size Population'.split())
df['City'] = 'Kampala', 'Arusha', 'Nyeri', 'Addis', 'Accra'
df['Size'] = 1000, 5000, 24000, 4300, 6000
df['Population'] = 250000, 150000, 230000, 500000, 100000
df

      City   Size  Population
0  Kampala   1000      250000
1   Arusha   5000      150000
2    Nyeri  24000      230000
3    Addis   4300      500000
4    Accra   6000      100000

In [11]:
#Querying the data to get size, population
df[['Size','Population']]

    Size  Population
0   1000      250000
1   5000      150000
2  24000      230000
3   4300      500000
4   6000      100000

In [12]:
#Adding a new column called Population desnity from population & Size
df['Population Density'] = df['Population'] / df['Size']
df

      City   Size  Population  Population Density
0  Kampala   1000      250000          250.000000
1   Arusha   5000      150000           30.000000
2    Nyeri  24000      230000            9.583333
3    Addis   4300      500000          116.279070
4    Accra   6000      100000           16.666667

### Dealing with already existing Data

In [2]:
new = pd.read_csv('covidset.csv')
new

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp
0,01/07/2020,1,7,2020,279,13,Afghanistan,AF,AFG,38041757.0,Asia
1,30/06/2020,30,6,2020,271,12,Afghanistan,AF,AFG,38041757.0,Asia
2,29/06/2020,29,6,2020,351,18,Afghanistan,AF,AFG,38041757.0,Asia
3,28/06/2020,28,6,2020,165,20,Afghanistan,AF,AFG,38041757.0,Asia
4,27/06/2020,27,6,2020,276,8,Afghanistan,AF,AFG,38041757.0,Asia
...,...,...,...,...,...,...,...,...,...,...,...
26977,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa
26978,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14645473.0,Africa
26979,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa
26980,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa
26981,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa

In [3]:
new.shape

(26982, 11)

In [4]:
new.columns

Index(['dateRep', 'day', 'month', 'year', 'cases', 'deaths',
       'countriesAndTerritories', 'geoId', 'countryterritoryCode',
       'popData2019', 'continentExp'],
      dtype='object')

#### Selection and Indexing

In [5]:
new[['cases','deaths']]

       cases  deaths
0        279      13
1        271      12
2        351      18
3        165      20
4        276       8
...      ...     ...
26977      0       0
26978      0       1
26979      0       0
26980      1       0
26981      1       0

[26982 rows x 2 columns]

*Data Frame columns are just series*

#### Selecting Rows

In [6]:
new.iloc[0]

dateRep                     01/07/2020
day                                  1
month                                7
year                              2020
cases                              279
deaths                              13
countriesAndTerritories    Afghanistan
geoId                               AF
countryterritoryCode               AFG
popData2019                 38041757.0
continentExp                      Asia
Name: 0, dtype: object

In [7]:
new.iloc[2]

dateRep                     29/06/2020
day                                 29
month                                6
year                              2020
cases                              351
deaths                              18
countriesAndTerritories    Afghanistan
geoId                               AF
countryterritoryCode               AFG
popData2019                 38041757.0
continentExp                      Asia
Name: 2, dtype: object

#### Selecting subset of rows and columns

In [8]:
new.loc[0,'cases']

279

In [9]:
new.loc[[0,2,4],['cases','deaths']]

   cases  deaths
0    279      13
2    351      18
4    276       8

#### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [10]:
new.columns
new[(new['month']==12)&(new['year']==2019)]

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp
173,31/12/2019,31,12,2019,0,0,Afghanistan,AF,AFG,38041757.0,Asia
467,31/12/2019,31,12,2019,0,0,Algeria,DZ,DZA,43053054.0,Africa
1172,31/12/2019,31,12,2019,0,0,Armenia,AM,ARM,2957728.0,Europe
1457,31/12/2019,31,12,2019,0,0,Australia,AU,AUS,25203200.0,Oceania
1641,31/12/2019,31,12,2019,0,0,Austria,AT,AUT,8858775.0,Europe
...,...,...,...,...,...,...,...,...,...,...,...
24507,31/12/2019,31,12,2019,0,0,Thailand,TH,THA,69625581.0,Asia
25544,31/12/2019,31,12,2019,0,0,United_Arab_Emirates,AE,ARE,9770526.0,Asia
25728,31/12/2019,31,12,2019,0,0,United_Kingdom,UK,GBR,66647112.0,Europe
26019,31/12/2019,31,12,2019,0,0,United_States_of_America,US,USA,329064917.0,America
26623,31/12/2019,31,12,2019,0,0,Vietnam,VN,VNM,96462108.0,Asia

In [11]:
#More than one condition
new.iloc[5475]

dateRep                      31/12/2019
day                                  31
month                                12
year                               2019
cases                                27
deaths                                0
countriesAndTerritories           China
geoId                                CN
countryterritoryCode                CHN
popData2019                1433783692.0
continentExp                       Asia
Name: 5475, dtype: object

#### Groupby

The groupby method allows you to group rows of data together and call aggregate functions

In [12]:
continentExp= new.groupby('continentExp')
continentExp

And then call aggregate methods off the object:

In [13]:
cov=['cases','deaths']
continentExp[cov].mean()

                   cases     deaths
continentExp
Africa         69.231926   1.734233
America       951.260179  45.086607
Asia          354.618629   8.829073
Europe        300.899236  23.646465
Oceania         9.692387   0.136831
Other          10.875000   0.109375

In [14]:
continentExp[cov].max()

              cases  deaths
continentExp
Africa         7210     168
America       54771    4928
Asia          19906    2003
Europe        11656    2004
Oceania         611       7
Other           134       2

In [15]:
continentExp[cov].count()

              cases  deaths
continentExp
Africa         5851    5851
America        5600    5600
Asia           6377    6377
Europe         8118    8118
Oceania         972     972
Other            64      64

In [16]:
continentExp['cases'].count()['Africa']

5851

In [17]:
continentExp[cov].describe()

               cases                                                    \
               count        mean          std     min  25%  50%    75%
continentExp
Africa        5851.0   69.231926   340.430511  -209.0  0.0  3.0   30.0
America       5600.0  951.260179  4422.759924 -2461.0  0.0  1.0   79.0
Asia          6377.0  354.618629  1210.533348     0.0  0.0  8.0  156.0
Europe        8118.0  300.899236  1085.048329  -766.0  0.0  9.0  103.0
Oceania        972.0    9.692387    45.777897     0.0  0.0  0.0    2.0
Other           64.0   10.875000    27.530358    -9.0  0.0  0.0    0.0

                       deaths                                                \
                  max   count       mean         std     min  25%  50%  75%
continentExp
Africa         7210.0  5851.0   1.734233    7.956224     0.0  0.0  0.0  1.0
America       54771.0  5600.0  45.086607  225.989320     0.0  0.0  0.0  2.0
Asia          19906.0  6377.0   8.829073   43.696429     0.0  0.0  0.0  2.0
Europe        11656.0  8118.0  23.646465  105.980585 -1918.0  0.0  0.0  4.0
Oceania         611.0   972.0   0.136831    0.595902     0.0  0.0  0.0  0.0
Other           134.0    64.0   0.109375    0.403051     0.0  0.0  0.0  0.0


                 max
continentExp
Africa         168.0
America       4928.0
Asia          2003.0
Europe        2004.0
Oceania          7.0
Other            2.0

In [19]:
continentExp['cases'].describe().transpose()

continentExp,Africa,America,Asia,Europe,Oceania,Other
count,5851.000000,5600.000000,6377.000000,8118.000000,972.000000,64.000000
mean,69.231926,951.260179,354.618629,300.899236,9.692387,10.875000
std,340.430511,4422.759924,1210.533348,1085.048329,45.777897,27.530358
min,-209.000000,-2461.000000,0.000000,-766.000000,0.000000,-9.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.000000,1.000000,8.000000,9.000000,0.000000,0.000000
75%,30.000000,79.000000,156.000000,103.000000,2.000000,0.000000
max,7210.000000,54771.000000,19906.000000,11656.000000,611.000000,134.000000

**Questions**
1. Number of rows and columns in the data
2. Number of columns in the data
3. Number of countries reported on in the data
4. Specify the countries captured in the data
5. Number of continents in the data
6. Which country (ies) is(are) included in the continent named 'Other' in the data?
7. How many African countries are in the data?
8. Which African country had the highest total cases in the month of June?
9. When did Uganda register the first covid case?
10. How many countries have zero deaths uptodate?

In [20]:
# number of rows and columns
new

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp
0,01/07/2020,1,7,2020,279,13,Afghanistan,AF,AFG,38041757.0,Asia
1,30/06/2020,30,6,2020,271,12,Afghanistan,AF,AFG,38041757.0,Asia
2,29/06/2020,29,6,2020,351,18,Afghanistan,AF,AFG,38041757.0,Asia
3,28/06/2020,28,6,2020,165,20,Afghanistan,AF,AFG,38041757.0,Asia
4,27/06/2020,27,6,2020,276,8,Afghanistan,AF,AFG,38041757.0,Asia
...,...,...,...,...,...,...,...,...,...,...,...
26977,25/03/2020,25,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa
26978,24/03/2020,24,3,2020,0,1,Zimbabwe,ZW,ZWE,14645473.0,Africa
26979,23/03/2020,23,3,2020,0,0,Zimbabwe,ZW,ZWE,14645473.0,Africa
26980,22/03/2020,22,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa
26981,21/03/2020,21,3,2020,1,0,Zimbabwe,ZW,ZWE,14645473.0,Africa

In [25]:
# number of countries
new['countriesAndTerritories'].nunique()

210

In [26]:
#4 specify the countries
a = new['countriesAndTerritories'].unique()
print ('The countries are:\n', a)

The countries are:
 ['Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola' 'Anguilla'
 'Antigua_and_Barbuda' 'Argentina' 'Armenia' 'Aruba' 'Australia' 'Austria'
 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan' 'Bolivia'
 'Bonaire, Saint Eustatius and Saba' 'Bosnia_and_Herzegovina' 'Botswana'
 'Brazil' 'British_Virgin_Islands' 'Brunei_Darussalam' 'Bulgaria'
 'Burkina_Faso' 'Burundi' 'Cambodia' 'Cameroon' 'Canada' 'Cape_Verde'
 'Cases_on_an_international_conveyance_Japan' 'Cayman_Islands'
 'Central_African_Republic' 'Chad' 'Chile' 'China' 'Colombia' 'Comoros'
 'Congo' 'Costa_Rica' 'Cote_dIvoire' 'Croatia' 'Cuba' 'Curaçao' 'Cyprus'
 'Czechia' 'Democratic_Republic_of_the_Congo' 'Denmark' 'Djibouti'
 'Dominica' 'Dominican_Republic' 'Ecuador' 'Egypt' 'El_Salvador'
 'Equatorial_Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia'
 'Falkland_Islands_(Malvinas)' 'Faroe_Islands' 'Fiji' 'Finland' 'France'
 'French_Polynesia' 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana'
 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guam' 'Guatemala' 'Guernsey'
 'Guinea' 'Guinea_Bissau' 'Guyana' 'Haiti' 'Holy_See' 'Honduras' 'Hungary'
 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Isle_of_Man'
 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya'
 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg' 'Madagascar'
 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Mauritania' 'Mauritius'
 'Mexico' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Montserrat'
 'Morocco' 'Mozambique' 'Myanmar' 'Namibia' 'Nepal' 'Netherlands'
 'New_Caledonia' 'New_Zealand' 'Nicaragua' 'Niger' 'Nigeria'
 'North_Macedonia' 'Northern_Mariana_Islands' 'Norway' 'Oman' 'Pakistan'
 'Palestine' 'Panama' 'Papua_New_Guinea' 'Paraguay' 'Peru' 'Philippines'
 'Poland' 'Portugal' 'Puerto_Rico' 'Qatar' 'Romania' 'Russia' 'Rwanda'
 'Saint_Kitts_and_Nevis' 'Saint_Lucia' 'Saint_Vincent_and_the_Grenadines'
 'San_Marino' 'Sao_Tome_and_Principe' 'Saudi_Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra_Leone' 'Singapore' 'Sint_Maarten' 'Slovakia'
 'Slovenia' 'Somalia' 'South_Africa' 'South_Korea' 'South_Sudan' 'Spain'
 'Sri_Lanka' 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Taiwan'
 'Tajikistan' 'Thailand' 'Timor_Leste' 'Togo' 'Trinidad_and_Tobago'
 'Tunisia' 'Turkey' 'Turks_and_Caicos_islands' 'Uganda' 'Ukraine'
 'United_Arab_Emirates' 'United_Kingdom' 'United_Republic_of_Tanzania'
 'United_States_of_America' 'United_States_Virgin_Islands' 'Uruguay'
 'Uzbekistan' 'Venezuela' 'Vietnam' 'Western_Sahara' 'Yemen' 'Zambia'
 'Zimbabwe']

In [27]:
#5 number of continents
new['continentExp'].nunique()

6

In [28]:
#6 countries in the continents named others
b = new[(new['continentExp']=='Other')]
print('The country(ies) are:',b['countriesAndTerritories'].unique())

The country(ies) are: ['Cases_on_an_international_conveyance_Japan']

In [29]:
#7 african countries present
c = new[(new['continentExp']=='Africa')]
print('There are',c['countriesAndTerritories'].nunique() ,'countries in Africa')

There are 55 countries in Africa

In [31]:
#8 african countries with highest total case in June
d = c[(c['month']== 6)]
print(d.groupby('countriesAndTerritories')['cases'].sum().idxmax())

South_Africa

In [32]:
#9 when Uganda registered first covid case
e = new[(new['countriesAndTerritories'] == 'Uganda')].reset_index()
e.drop('index',axis= 1,inplace = True)

In [40]:
e['dateRep_new'] = pd.to_datetime(e['dateRep'])
print(e.groupby('countriesAndTerritories')['dateRep'].min()['Uganda'])

01/04/2020

C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '30/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '29/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '28/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '27/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '26/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '25/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '24/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '23/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '22/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '21/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '20/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '19/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '18/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '17/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '16/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '15/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '14/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '13/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '31/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '30/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '29/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '28/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '27/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '26/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '25/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '24/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '23/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '22/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '21/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '20/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '19/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '18/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '17/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '16/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '15/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '14/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '13/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '30/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '29/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '28/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '27/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '26/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '25/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '24/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '23/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '22/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '21/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '20/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '19/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '18/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '17/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '16/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '15/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '14/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '13/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '31/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '30/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '29/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '28/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '27/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '26/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '25/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '24/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '23/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])
C:\Users\HP\AppData\Local\Temp\ipykernel_4868\1864151131.py:1: UserWarning: Parsing '22/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  e['dateRep_new'] = pd.to_datetime(e['dateRep'])

In [41]:
#10 countries with 0 deaths 
f = new.groupby('countriesAndTerritories')
f['deaths'].sum().value_counts().iloc[0]

27

## Exercise

11. Which continent had the highest number of deaths in March?
12. Which African country registered the first case?
13. In which month are the most cases reported?
14. Is there a relation between the cases in America and the cases in Asia?
15. Which European country has the highest frequency in number of deaths reported?
16. What is the name of the country with the lowest daily reported cases in the month of March
17. On average, how many cases were registered in Asia and Africa from March to June?
18. Based on the African countries represented in the data, introduce a new column called 'Region' and answer the questions below. [Link to the Regions](https://en.wikipedia.org/wiki/List_of_regions_of_Africa)
19. Which region has had the highest number of registered cases overtime?
20. Which region has registered a drop in the number of registered cases over time?

In [61]:
#11 continents with highest no of deaths in march
h = new[(new['month']== 3)].groupby('continentExp')
h['deaths'].sum().idxmax()

'Europe'

In [57]:
#12 african country with the first case
k = new[new['continentExp'] == 'Africa']
k['dateRep_new'] = pd.to_datetime(k['dateRep'])
k['dateRep_new'].idxmin()

print(k.loc[k['dateRep_new'].idxmin(),'countriesAndTerritories'])

Algeria

C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '30/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '29/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '28/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '27/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '26/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '25/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '24/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '23/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '20/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '17/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '16/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '14/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/06/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '31/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '30/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '29/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '28/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '27/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '26/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '25/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '24/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '23/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '20/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '17/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '16/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '14/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/05/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '30/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '29/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '28/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '27/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '26/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '25/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '24/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '23/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '20/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '17/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '16/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '14/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/04/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '31/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '30/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '29/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '28/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '27/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '26/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '25/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '24/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '23/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '20/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '17/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '16/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\Users\HP\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15/03/2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)

In [60]:
#13 the month with most cases reported
p = new.groupby('month')['cases'].sum().idxmax()
p

6

In [ ]:
#14

In [71]:
#15 european country with highest frequency of deaths
q = new[(new['continentExp']=='Europe')]
print(q.groupby('countriesAndTerritories')['deaths'].count().idxmax())

Austria

In [82]:
#16 country with lowest daily reported cases in march
r = new[(new['month']== 3)]
r.groupby('countriesAndTerritories')['cases'].sum().idxmin()

'Cases_on_an_international_conveyance_Japan'

In [98]:
#17 on average how many cases were registered in asia and africa from march to june
s = new[(new['month']== 3 & 4 & 5 & 6)]
r.groupby('continentExp')['cases'].mean()

continentExp
Africa       7.100968
America    257.732240
Asia        91.744658
Europe     325.128690
Oceania     46.473684
Other       -3.000000
Name: cases, dtype: float64